server:
  port: 8080
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

spring:
  profiles:
    active: ${SPRING_PROFILE:local}  # 默认使用本地开发环境配置
    
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# Actuator + Prometheus 监控
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
